title: Yan Liu's Homepage
page-top-title: Yan Liu
top-section-bg-text: Computer Science
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
background-interval-ms: 7000
background-overlay: 0.52

##page footing
copyright-text: '&copy; Yan Liu 2023-2026. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/lltopk
license-link:
  text: License
  href: https://github.com/lltopk/lltopk.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: Yan Liu&ensp;|&ensp;刘 岩
    href: '#page-top' # Default to '#<id>' if not specified
  # - id: publications
  #   nav: PUBLICATIONS
  #   title: PUBLICATIONS
  #   icon: bi-file-text-fill
  # - id: awards
  #   nav: AWARDS
  #   title: AWARDS
  #   icon: bi-award-fill
